### ISSUE TITLE
Create save_data function with savedata alias

### ISSUE THREAD

**Issue by billallen256** [dspftw/dspftw#12]

**Comment by willispetersen** [comment]
Function should take an input array and save it into a file given the same data types as specified in the load_data function.  The inputs for this function should be:

filename
array
data type
endianness (default = native machine format)

Should return the number of elements that it saves.

**Comment by billallen256** [comment]
Working on this now...

**Comment by billallen256** [comment]
Added in 4d3d93a2ff3f0150192315cffedde74e3e0ecabe
