### ISSUE TITLE
Overload matplotlib.pyplot.plot function so that it takes complex input data

### ISSUE THREAD

**Issue by willispetersen** [dspftw/dspftw#3]
Either overload the plot function or create a separate function (maybe plotc) that will plot complex data.

**Comment by gershwinlabs** [comment]
I added this as `plot_complex()`, and aliased it as `plotc()` in `plotting.py`.  Keyword arguments like (eg. `color` below) are passed through.

```python
import numpy as np
import matplotlib.pyplot as plt
import dspftw

complex_data = np.array([1+0j, 0+1j, -1+0j, 0-1j])
fig = dspftw.plotc(complex_data, color='red')
plt.show()
```

**Comment by willispetersen** [comment]
I changed plot_complex so that it works exactly like plot.  So you can now put multiple things in there and have it plot them.  For example:

```python3
import numpy as np
import matplotlib.pyplot as plt
import dspftw.plotting as dp

a = np.random.randn(5, 3)+1J*np.random.randn(5, 3)
b = np.random.randn(100)+1J*np.random.randn(100) + 4+4J

plt.figure()
plt.plot(a.real, a.imag, '*-', b.real, b.imag, 'o--', markersize=5)
dp.plotc(a, '*-', b, 'o--', markersize=5)
```

Those two plots should be the same.  I'd like to avoid plt.scatter since it doesn't have as many options as plt.plot.  I'd like to stick with plt.plot as the main function to emulate.

**Comment by willispetersen** [comment]
Okay... I obviously don't know what I'm doing with pull requests.  Whatevs!

I've made another commit for this fix because I didn't like how it was spitting out stuff rather than just plotting it.  That's been fixed.  Hopefully that pull request can be seen relative to this issue.
