### ISSUE TITLE
Create load_data function with loaddata alias

### ISSUE THREAD

**Issue by billallen256** [dspftw/dspftw#9]

**Comment by willispetersen** [comment]
Function should load all the different types of homogenous data that is byte based (i.e. doesn't have to load bits).  Inputs should be:

filename
date type
number of units to load (default = All)
starting unit to load from (default = 0)
endianness (default = native machine format)

Should return a numpy array containing the values.

The values that should be possible are:
uint8
uint16
uint32
uint64
int8
int16
int32
int64
float32
float64
float128 (if that's a thing?)

and any other normal data that is possible.  It seems like there are a lot of different names for the same kind of thing.  I'd like to be able to handle any of the different types found in "help fread" in Octave.  Here's a readout of that:

```
     "uint8" (default)
          8-bit unsigned integer.

     "int8"
     "integer*1"
          8-bit signed integer.

     "uint16"
     "ushort"
     "unsigned short"
          16-bit unsigned integer.

     "int16"
     "integer*2"
     "short"
          16-bit signed integer.

     "uint"
     "uint32"
     "unsigned int"
     "ulong"
     "unsigned long"
          32-bit unsigned integer.

     "int"
     "int32"
     "integer*4"
     "long"
          32-bit signed integer.

     "uint64"
          64-bit unsigned integer.

     "int64"
     "integer*8"
          64-bit signed integer.

     "single"
     "float"
     "float32"
     "real*4"
          32-bit floating point number.

     "double"
     "float64"
     "real*8"
          64-bit floating point number.

     "char"
     "char*1"
          8-bit single character.

     "uchar"
     "unsigned char"
          8-bit unsigned character.

     "schar"
     "signed char"
          8-bit signed character.
```

**Comment by gershwinlabs** [comment]
Starting work on this...

**Comment by gershwinlabs** [comment]
We should avoid ambiguous types like `int`, `uint`, `float`, `short`, `long`, etc.  We're not animals.

**Comment by gershwinlabs** [comment]
This should be ready for testing once we have data.
